config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :projects, only: [:index, :show]
  get "/about", to: "about#index"
  get "/projects/category/:name", to: "projects#index", :as => :category


  # scope "/:locale" do
 	# root 'welcome#index'
	# resources :projects, only: [:index, :show]
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cd.rb
class Cd < ApplicationRecord
	belongs_to :folder

	default_scope -> { order('cd_id DESC') }
end

app/models/cycle.rb
class Cycle < ApplicationRecord
	mount_uploader :image ,ImageUploader
	validates :image, presence: true

	default_scope -> { order('sorting DESC') }

	def status
		self.publish
	end
end

app/models/folder.rb
class Folder < ApplicationRecord
	has_many :cds

	default_scope -> { order('foldername DESC') }
end

app/models/gallery.rb
class Gallery < ApplicationRecord
	mount_uploader :name, GalleryUploader
	# serialize :name
	belongs_to :project

	default_scope -> { order("sorting DESC") }
end

app/models/project.rb
class Project < ApplicationRecord
	require 'csv'

	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings
	has_many :gallerys, -> {  order('name asc') }, dependent: :destroy
	accepts_nested_attributes_for :gallerys
	mount_uploader :thumb, AvatarUploader
	validates :title, presence: true

	default_scope -> { order('sorting DESC') }
	scope :category, ->(category) { joins(:tags).where(:tags => { "name" => category }).where(published: true).order('sorting DESC') }

	def tag_list
	    tags.map(&:name).join(', ')
	end

	def tag_list=(names)
    	self.tags = names.reject(&:blank?).map do |item|
      		Tag.where(name: item.strip).first_or_create!
    	end
   	end

   	def tag_items
		tags.map(&:name)
	end

	def tag_ids=(ids)
	    self.tags = Array(ids).reject(&:blank?).map { |id|
	      (id =~ /^\d+$/) ? Tag.find(id) : Tag.new(name: id)
	    }
	end

	def checksorting
		if !self.sorting
			# get maximun sorting
			if Project.any?
				Project.maximum("sorting") + 10
			else
				10
			end
		else
			self.sorting
		end
	end

	def featured
		self.feature
	end

	def status
		self.published
	end

	def gallery_items
		gallerys.map(&:name).join(', ')
	end

	def img_name(id)
		Gallery.find(id)
	end

	def delImg
	end

	def previous
		Project.where(["sorting > ?", sorting]).where(published: true).last
	end

	def next
		Project.where(["sorting < ?", sorting]).where(published: true).first
	end

	# export to csv
	def self.to_csv
	    attributes = %w{id title}

	    CSV.generate(headers: true) do |csv|
	      csv << attributes

	      all.each do |user|
	        csv << attributes.map{ |attr| user.send(attr) }
	      end
	    end
	 end

	def name
		"#{title}"
	end
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :projects, through: :taggings
	validates :name, presence: true
	default_scope -> { order('sorting DESC') }

	def tag_title
		@name = Tag.find(1)
	end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :project
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pagy::Backend
	before_action :set_locale

	def set_locale
	  # 可以將 ["en", "zh-TW"] 設定為 VALID_LANG 放到 config/environment.rb 中
	  if params[:locale] && I18n.available_locales.include?( params[:locale].to_sym )
	    session[:locale] = params[:locale]
	  end

	  I18n.locale = session[:locale] || I18n.default_locale
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		if params[:name]
			# @posts = Project.category(params[:category])
			@pagy, @posts = pagy(Project.category(params[:name]))
		else
			#@posts = Project.where(published: true)
			@pagy, @posts = pagy(Project.where(published: true))
		end

		@tags = Tag.all()

		# ----------------------------
		@projects = Project.all

		respond_to do |format|
			format.html
			format.csv { send_data @projects.to_csv, filename: "project-#{Date.today}.csv" }
		end
	end

	# GET /projects/1
	def show
		@post = Project.find(params[:id])
		if @post.published == false
			redirect_to projects_path, notice: '作品未發佈'
		end
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
		@tags = Tag.all()
	end

	def show
		@post = Tag.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@posts = Project.where(published: true, feature: true).limit(6)
  	# @cycle = Cycle.where(publish: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include Pagy::Frontend

	def current_class?(path)
    	'active' if request.path == path
  	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	require 'net/http'

	YOUTUBE_REGEX = %r(^(http[s]*:\/\/)?(www.)?(youtube.com|youtu.be)\/(watch\?v=){0,1}([a-zA-Z0-9_-]{11}))
	VIMEO_REGEX = /https?:\/\/(?:[\w]+\.)*vimeo\.com(?:[\/\w]*\/?)?\/(?<id>[0-9]+)[^\s]*/

	def showAllTag
		Tag.all
	end

	def tag_title(id)
		Tag.select("name").find(id)
	end

	def getGalleryImg(id)
		img = Gallery.find(id)
		content_tag :div,image_tag(img.name.url, class: "img-responsive", data: { "original": img.name.url}), class: "img-item fade"
	end

	def get_video_iframe(url)
		if find_vimeo_id(url)
		  @videoid = find_vimeo_id(url)
		  get_vimeo_iframe(@videoid)
		elsif find_youtube_id(url)
		  @videoid = find_youtube_id(url)
		  get_youtube_iframe(@videoid)
		end
	end

	def find_vimeo_id(url)
		matches = VIMEO_REGEX.match url.to_str
		if matches
			@videoid = matches[:id]
		end
	end

	def find_youtube_id(url)
		matches = YOUTUBE_REGEX.match url.to_str
		if matches
		  @videoid = matches[6] || matches[5]
		end
	end

	
	def get_youtube_iframe(videoid)
	    result = %(<iframe title="YouTube video player" width="100%"
	                height="960" src="//www.youtube.com/embed/#{ videoid }"
	                frameborder="0" allowfullscreen></iframe>)
	    result.html_safe
	end

	def get_vimeo_iframe(videoid)
	    uri = "https://vimeo.com/api/oembed.json?url=https%3A//vimeo.com/#{ videoid }&width=100%&height=960"
	    response = Net::HTTP.get( URI.parse( uri ))
	    json = JSON.parse response
	    json['html'].html_safe
	end
end

app/helpers/tags_helper.rb
module TagsHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/_content.html.erb
<article id="article" class="article">
	<p>我是陳信樺，出生於1982年，最高學歷為遠東科技大學資訊管理系。
	個性穩重，喜歡運動、喜歡思考、喜歡解決問題、喜歡嘗試寫一些不同的功能。</p>

	<p>進入洋蔥設計後，接觸到UI設計，了解好的網頁設計能夠幫助企業行銷，因此喜歡鑽研網頁前後端設計。</p>

	<p>因現今網頁技術進步迅速，因此能去外面上課不斷接觸不同技術，
	從早期的 Flash 到 CSS3、HTML5，
	PHP 到 Ruby on Rails</p>

	<section class="section">
		<h3>技能</h3>
		<div class="row">
			<div class="col-md-4">
				<h4>前端</h4>
				<ul>
					<li>Bootstrap</li>
					<li>CSS3 ／ CSS3 svg 動態</li>
					<li>SASS / SCSS</li>
					<li>Jquery</li>
					<li>Git</li>
					<li>React</li>
					<li>RWD網頁切版</li>
					<li>具有介接 FB Login、Google Service API 經驗</li>
				</ul>
			</div>
			<div class="col-md-4">
				<h4>CMS</h4>
				<ul>
					<li>Wordpress建置</li>
					<li>Joomla建置 / 模組開發</li>	
				</ul>
			</div>
			<div class="col-md-4">
				<h4>後端</h4>
				<ul>
					<li>PHP</li>
					<li>Ruby on Rails</li>
				</ul>
			</div>
		</div>
	</section>
	<section class="section">
		<h3>工作經歷</h3>
		<ul>
			<li>
				<h4>洋蔥設計前端工程師</h4>
				<p>負責將設計師 sketch 網頁化、製作 jquery 動態、API串接</p>
				<%= link_to "作品連結",projects_path %>
 			</li>
		</ul>
	</section>
	<section class="section">
		<h3>學歷</h3>
		<ul>
			<li>遠東技術學院 － 資訊管理系</li>
			<li>亞東技術學院 － 工業管理系</li>
		</ul>
	</section>
</article>

app/views/about/content.html.erb
<article id="article" class="article">
	<p>我是陳信樺，出生於1982年，最高學歷為遠東科技大學資訊管理系。
	個性穩重，喜歡運動、喜歡思考、喜歡解決問題、喜歡嘗試寫一些不同的功能。</p>

	<p>進入洋蔥設計後，接觸到UI設計，了解好的網頁設計能夠幫助企業行銷，因此喜歡鑽研網頁前後端設計。</p>

	<p>因現今網頁技術進步迅速，因此能去外面上課不斷接觸不同技術，
	從早期的 Flash 到 CSS3、HTML5，
	PHP 到 Ruby on Rails</p>

	<section class="section">
		<h3>技能</h3>
		<div class="row">
			<div class="col-md-4">
				<h4>前端</h4>
				<ul>
					<li>Bootstrap</li>
					<li>CSS3 ／ CSS3 svg 動態</li>
					<li>SASS / SCSS</li>
					<li>Jquery</li>
					<li>Git</li>
					<li>React</li>
					<li>RWD網頁切版</li>
					<li>具有介接 FB Login、Google Service API 經驗</li>
				</ul>
			</div>
			<div class="col-md-4">
				<h4>CMS</h4>
				<ul>
					<li>Wordpress建置</li>
					<li>Joomla建置 / 模組開發</li>	
				</ul>
			</div>
			<div class="col-md-4">
				<h4>後端</h4>
				<ul>
					<li>PHP</li>
					<li>Ruby on Rails</li>
				</ul>
			</div>
		</div>
	</section>
	<section class="section">
		<h3>工作經歷</h3>
		<ul>
			<li>
				<h4>洋蔥設計前端工程師</h4>
				<p>負責將設計師 sketch 網頁化、製作 jquery 動態、API串接</p>
				<%= link_to "作品連結",projects_path %>
 			</li>
		</ul>
	</section>
	<section class="section">
		<h3>學歷</h3>
		<ul>
			<li>遠東技術學院 － 資訊管理系</li>
			<li>亞東技術學院 － 工業管理系</li>
		</ul>
	</section>
</article>

app/views/about/index.html.erb
<article id="article" class="article">
	<p>我是陳信樺，出生於1982年，最高學歷為遠東科技大學資訊管理系。
	個性穩重，喜歡運動、喜歡思考、喜歡解決問題、喜歡嘗試寫一些不同的功能。</p>

	<p>進入洋蔥設計後，接觸到UI設計，了解好的網頁設計能夠幫助企業行銷，因此喜歡鑽研網頁前後端設計。</p>

	<p>因現今網頁技術進步迅速，因此能去外面上課不斷接觸不同技術，
	從早期的 Flash 到 CSS3、HTML5，
	PHP 到 Ruby on Rails</p>

	<section class="section">
		<h3>技能</h3>
		<div class="row">
			<div class="col-md-4">
				<h4>前端</h4>
				<ul>
					<li>Bootstrap</li>
					<li>CSS3 ／ CSS3 svg 動態</li>
					<li>SASS / SCSS</li>
					<li>Jquery</li>
					<li>Git</li>
					<li>Vue</li>
					<li>RESTful API 串接</li>
					<li>FB Login、Google Map API</li>
					<li>AWS EC2 Ubuntu Server 建置</li>
				</ul>
			</div>
			<div class="col-md-4">
				<h4>CMS</h4>
				<ul>
					<li>Wordpress建置</li>
					<li>Joomla建置 / 模組開發</li>	
				</ul>
			</div>
			<div class="col-md-4">
				<h4>後端</h4>
				<ul>
					<li>PHP</li>
					<li>Ruby on Rails</li>
				</ul>
			</div>
		</div>
	</section>
	<section class="section">
		<h3>工作經歷</h3>
		<ul>
			<li>
				<h4>洋蔥設計前端工程師</h4>
				<p>負責將UI設計師 sketch 檔案網頁化、Jquery / SVG動態製作、API串接</p>
				<%= link_to "作品連結",projects_path %>
 			</li>
		</ul>
	</section>
	<section class="section">
		<h3>學歷</h3>
		<ul>
			<li>遠東技術學院 － 資訊管理系</li>
			<li>亞東技術學院 － 工業管理系</li>
		</ul>
	</section>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<% if I18n.locale == :en %>
<html lang="en">
<% else %>
<html lang="zh-hant">
<% end %>
  <head>
    <title>Hsinhua</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8">
    <meta name="Description" content="" />
    <meta name="Keywords" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name='turbolinks-cache-control' content='no-cache'>
    <!-- <meta name="turbolinks-root" content="/app"> -->
    <meta name="turbolinks-visit-control" content="reload">
    <meta name="author" content="hsinhua" />
    <meta name="copyright" content="hsinhua" />
    <link href="favicon.ico" rel="shortcut icon" />
    <meta property="og:title" content="Hsinhua">
    <meta property="og:site_name" content="Hsinhua"/>
    <meta property="og:type" content="website">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <meta name="robots" content="noindex">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <link href="https://fonts.googleapis.com/css?family=Staatliches&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <main id="main" role="main" class="container">
      <%= render "shared/header" %>
      <%= yield %>
      <%= render "shared/footer" %>
    </main>
  </body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/projects/index.html.erb
<div class="page">
	<%= render "shared/taglist" %>
	<%=
		# if params[:name]
		# 	content_tag :h2, params[:name]
		# else
		# 	content_tag :h2, "All"
		# end
	%>

	<div id="projects" class="list">
		<div class="row">
			<% @posts.each do |post| %>
				<%= render partial: "shared/item", locals: {post: post, column: 3} %>
			<% end %>
		</div>
	</div> <!-- /.list -->
	<%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
</div> <!-- /.page -->

app/views/projects/show.html.erb
<article id="project" class="page">
	<% if @post.published %>
	<div class="gallery">
		<% if @post.video != "" %>
			<div class="img-item">
				<div class="embed-responsive embed-responsive-16by9">
					<%= get_video_iframe(@post.video) %>
				</div>
			</div>
		<% end %>

		<% imgs = @post.gallery_ids %>
		<% imgs.each do |imgid| %>
		<%= getGalleryImg(imgid) %>
		<% 	end %>
	</div> <!-- /gallery -->
	<% if I18n.locale == :en %>
	<div class="info en">

	<h1><%=@post.title_en %></h1>
	<%= @post.desc_en.html_safe %>
	</div> <!-- /info -->

	<% else %>

	<div class="info tw">
	<h1><%=@post.title %></h1>
	<%= @post.desc.html_safe %>
	<%= link_to "Link", @post.url, class: "btn-link", target: "_blank" %>
	</div>

	<% end %>
	<hr class="clear">
	<div class="control hidden-xs">
		<div class="row">
			<%= link_to content_tag(:span,'Previous project'), @post.previous, class: 'col-xs-3', "data-turbolink": false %>
			<%= link_to content_tag(:span,'Back'), projects_path, class: 'col-xs-6 text-center', "data-turbolink": false %>
			<%= link_to content_tag(:span,'Next project'), @post.next, class: 'col-xs-3 text-right', "data-turbolink": false  %>
		</div>
	</div> <!-- /control -->

	<% else %>
		<!-- <p>作品未發佈</p> -->
	<% end # end if published %>
</article>

app/views/shared/_cycle.html.erb
<div id="full" class="carousel">
	<div class="carousel-inner slider">
	<% @cycle.each do |img| %>
	  <div class="carousel-item">
	  	<% cycleImg = img.image.url if img.image? %>
	  	<div class="pic" style="background-image: url('<%= cycleImg %>'); "></div>
	  </div>
	  <!-- <div class="carousel-item">
	  	<div class="pic" style="background-image: url('<%= asset_path("gutenberg.jpg") %>'); "></div>
	  </div>
	  <div class="carousel-item">
	  	<div class="pic" style="background-image: url('<%= asset_path("holdthattiger.jpg") %>'); "></div>
	  </div>
	  <div class="carousel-item">
	  	<div class="pic" style="background-image: url('<%= asset_path("tolaku.jpg") %>'); "></div>
	  </div> -->
	<% end %>
	</div> <!-- /carousel-inner -->
</div>

app/views/shared/_footer.html.erb
<footer id="footer">
  <div class="row">
    <p class="contact col-xs-10">0952348529<br />
      <%=mail_to 'yha0971@gmail.com','yha0971@gmail.com' %>
    </p>
    <div class="col-xs-2 text-right">
      <%=link_to '↑', '#top', class: "gotop" %> 
    </div>
  </div> <!-- /row -->
  <div class="row">
    <div class="col-md-6">
      <p class="copyright">&copy; 2019 Hinhua</p>
    </div>
    <div class="col-md-6">
    </div>
  </div> <!-- /row -->
</footer>

app/views/shared/_header.html.erb
<header id="header">
  <%  # if homepage
  if current_page?(url_for(:controller => 'welcome', :action => 'index'))

  end
  %>

  <nav id="mainNav" class="navbar navbar-expand-lg">
    <a class="navbar-brand" data-turbolinks="true" href="/">Hsinhua</a>

    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <%= link_to "ABOUT", about_path, class: "nav-link btn-list" %>
      </li>
      <li class="nav-item">
        <% class_name = current_page?(projects_path) ? 'nav-link active' : 'nav-link' %>
        <%= link_to "WORK", projects_path, :class => class_name %>
      </li>
      <li class="nav-item">
        <%= link_to "GITHUB","https://github.com/hsinhuachen/",target: "_blank", class: "nav-link btn-list" %>
      </li>
    </ul>
  </nav>
</header>

app/views/shared/_item.html.erb
<% if column == 2 %>
<div class="project-item col-md-6">
<% elsif column == 3 %>
<div class="project-item col-md-4 col-sm-6">
<% else %>
<div class="project-item col-md-3 col-sm-6">
<% end %>
	<div class="thumb">
		<% #link_to "", project_path(I18n.locale, id: post.id), class: "item-link" %>
		<%= link_to "", post, class: "item-link"  %>
		<div class="mask fade">
		</div>
		<%= image_tag post.thumb.url, class: 'img-responsive', alt: post.title %>
	</div> <!-- /thumb -->
	<h3 class="project-name"><%=post.title %></h3>
	<% #content_tag :p, post.tag_list %>
</div>

app/views/shared/_pagination.html.haml
-# This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
-# calls with the actual strings ("‹ Prev", "Next ›", "…").

-# The link variable is set to a proc that returns the link tag.
-# Usage: link.call( page_number [, text [, extra_attributes_string ]])

- link = pagy_link_proc(pagy)

%nav.pagy_nav.pagination{"aria-label" => "pager", :role => "navigation"}

  - if pagy.prev
    %span.page.prev!= link.call(pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"')
  - else
    %span.page.prev.disabled!= pagy_t('pagy.nav.prev')

  - pagy.series.each do |item|       # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36]
    - if item.is_a?(Integer)         # page link
      %span.page
        != link.call(item)

    - elsif item.is_a?(String)       # current page
      %span.page.current= item

    - elsif item == :gap             # page gap
      %span.page.gap!= pagy_t('pagy.nav.gap')

  - if pagy.next
    %span.page.next!= link.call(pagy.next, pagy_t('pagy.nav.next'), 'aria-label="next"')
  - else
    %span.page.next.disabled!= pagy_t('pagy.nav.next')


    

app/views/shared/_taglist.html.erb
<div class="category">
	<%= if params[:name]
			link_to content_tag(:span,'All'), projects_path, class: ''
		else
			link_to content_tag(:span,'All'), projects_path, class: 'active'
		end
	%>
	<% @tags.each do |tag|  %>
		<%=
			if params[:name] && params[:name] == tag.name
				link_to content_tag(:span,tag.name), projects_path(category: tag.name), class: 'active'
			else
				#link_to content_tag(:span,tag.name), projects_path(category: tag.name)
				link_to content_tag(:span,tag.name), category_path(tag.name)
			end
		%>
	<% end %>
</div>

app/views/tags/index.html.erb
<div class="page">
	<%= render "shared/taglist" %>
	<%=
		if params[:id]
			content_tag :h2, "aaa"
		else
			content_tag :h2, "All"
		end
	%>
</div>

app/views/tags/show.html.erb
<div class="page">
	<div class="category">
		
	</div>
</div>

app/views/trestle/application/_header.html.erb
<header class="content-header">
  <div class="content-header-title">
    <h1>
      <%= content_for(:title) %>
    </h1>

    <% unless local_assigns.fetch(:hide_breadcrumbs, false) %>
    <ol class="breadcrumb">
      <% breadcrumbs.each do |breadcrumb| %>
        <li class="breadcrumb-item<% if breadcrumb == breadcrumbs.last %> active<% end %>">
          <%= link_to breadcrumb.label, breadcrumb.path %>
        </li>
      <% end %>
    </ol>
    <% end %>
  </div>

  <div class="content-header-toolbars">
    <div class="btn-toolbar primary-toolbar" role="toolbar">
      <%= render_toolbar(toolbar(:primary)) %>
      <%= deprecated_toolbar(:primary) %>
    </div>

    <div class="btn-toolbar secondary-toolbar" role="toolbar">
      <%= render_toolbar(toolbar(:secondary)) %>
      <%= deprecated_toolbar(:secondary) %>
    </div>

    <!-- <div class="btn-toolbar third-toolbar" role="toolbar">
      <%= link_to content_tag(:i, 'Export'), export_projects_admin_index_path, method: :post, class: 'btn-new-resource btn btn-success has-icon' %>
    </div> -->
  </div>
</header>

app/views/welcome/index.html.erb
<!-- <div id="loading" class="loadwrap"></div> -->
<div id="home" class="page">
	<% ##render partial: "shared/cycle", locals: {cycle: @cycle} %>
	<div class="homelist list">
		<div class="row">
			<% @posts.each do |post| %>
				<%= render partial: "shared/item", locals: {post: post, column: 3} %>
			<% end %>
		</div>
	</div> <!-- /list -->

	<%= link_to content_tag(:span, 'View all works'), projects_path, class: 'more text-center' %>
</div> <!-- /main -->